# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.27
_src_path: https://github.com/OCA/oca-addons-repo-template.git
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: true
enable_checklog_odoo: true
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: OCB
odoo_version: 18.0
org_name: Akretion
org_slug: Akretion
rebel_module_groups: []
repo_description: Convert data (file or sql query) to polars dataframe to ensure transformation
    in the same way
repo_name: Polars for odoo
repo_slug: polars-odoo
repo_website: https://github.com/akretion/polars-odoo
use_pyproject_toml: true
use_ruff: true

